# -*- coding: utf-8 -*-
"""205124066_LAB3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5ueuUuTW6qxjXqRMJVmLoK1yqIxxzAL
"""

import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

X,y = make_moons(n_samples = 1000 , noise = 0.2 , random_state= 42)

x_train , x_test, y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state=42)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

model= Sequential()
model.add(Dense(5 , activation='relu' , input_shape=(2,)))
model.add(Dense(1 , activation='sigmoid'))
model.compile(optimizer=Adam(learning_rate=0.4), loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(x_train_scaled , y_train, epochs=50 , verbose = 1 , validation_data = (x_test_scaled , y_test))

# Evaluate the model on test data
results = model.evaluate(x_test_scaled, y_test)
print(f"Test Loss: {results[0]}, Test Accuracy: {results[1]}")

import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam


X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


model = Sequential()


model.add(Dense(10, input_shape=(2,), activation='relu'))


model.add(Dense(1, activation='sigmoid'))


model.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])


history = model.fit(X_train_scaled, y_train, epochs=100, verbose=1, validation_data=(X_test_scaled, y_test))


results = model.evaluate(X_test_scaled, y_test)
print(f"Test Loss: {results[0]}, Test Accuracy: {results[1]}")

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_datasets as tfds


img_size = (224, 224)
batch_size = 32
num_classes = 5
AUTOTUNE = tf.data.AUTOTUNE

print("Using TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices("GPU"))


(train_ds, val_ds), ds_info = tfds.load(
    "tf_flowers",
    split=["train[:80%]", "train[80%:]"],
    as_supervised=True,
    with_info=True
)


def preprocess(image, label):
    image = tf.image.resize(image, img_size)
    image = tf.cast(image, tf.float32)
    return image, label

train_ds = (
    train_ds
    .map(preprocess, num_parallel_calls=AUTOTUNE)
    .shuffle(1000)
    .batch(batch_size)
    .prefetch(AUTOTUNE)
)

val_ds = (
    val_ds
    .map(preprocess, num_parallel_calls=AUTOTUNE)
    .batch(batch_size)
    .prefetch(AUTOTUNE)
)


data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
])


base_model = keras.applications.ResNet50(
    include_top=False,
    weights="imagenet",
    input_shape=img_size + (3,)
)
base_model.trainable = False


inputs = keras.Input(shape=img_size + (3,))
x = data_augmentation(inputs)
x = keras.applications.resnet50.preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(256, activation="relu")(x)
outputs = layers.Dense(num_classes, activation="softmax")(x)

model = keras.Model(inputs, outputs)


model.compile(
    optimizer=keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("\n🔹 Stage 1: Training classifier head")
model.fit(train_ds, epochs=5, validation_data=val_ds)


base_model.trainable = True
for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=keras.optimizers.Adam(1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("\n🔹 Stage 2: Fine-tuning ResNet")
model.fit(train_ds, epochs=5, validation_data=val_ds)


loss, acc = model.evaluate(val_ds)
print(f"\n✅ Final Validation Accuracy: {acc:.4f}")