# -*- coding: utf-8 -*-
"""205124066_LAB_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ixg8wS9UYdyW3bziZV1-ersz4WGyVISs
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

latent_dim = 100

# -----------------------------
# Generator
# -----------------------------
def build_generator():
    model = keras.Sequential([
        layers.Input(shape=(latent_dim,)),
        layers.Dense(7*7*128),
        layers.Reshape((7,7,128)),
        layers.BatchNormalization(),
        layers.Conv2DTranspose(64, 4, strides=2, padding="same"),
        layers.LeakyReLU(0.2),
        layers.BatchNormalization(),
        layers.Conv2DTranspose(1, 4, strides=2, padding="same", activation="tanh")
    ])
    return model

# -----------------------------
# Discriminator
# -----------------------------
def build_discriminator():
    model = keras.Sequential([
        layers.Input(shape=(28,28,1)),
        layers.Conv2D(64, 4, strides=2, padding="same"),
        layers.LeakyReLU(0.2),
        layers.Conv2D(128, 4, strides=2, padding="same"),
        layers.LeakyReLU(0.2),
        layers.Flatten(),
        layers.Dense(1, activation="sigmoid")
    ])
    return model

generator = build_generator()
discriminator = build_discriminator()

# Compile Discriminator
discriminator.compile(
    optimizer=keras.optimizers.Adam(learning_rate=2e-4, beta_1=0.5),
    loss="binary_crossentropy"
)

# -----------------------------
# GAN Model
# -----------------------------
discriminator.trainable = False

z = keras.Input(shape=(latent_dim,))
fake_img = generator(z)
validity = discriminator(fake_img)

gan = keras.Model(z, validity)
gan.compile(
    optimizer=keras.optimizers.Adam(learning_rate=2e-4, beta_1=0.5),
    loss="binary_crossentropy"
)

# -----------------------------
# Load MNIST
# -----------------------------
(x_train, _), _ = keras.datasets.mnist.load_data()

x_train = (x_train.astype("float32") - 127.5) / 127.5
x_train = x_train[..., None]

batch_size = 128
dataset = tf.data.Dataset.from_tensor_slices(x_train).shuffle(10000).batch(batch_size)

# -----------------------------
# Function to Generate Images
# -----------------------------
def generate_and_plot_images(generator, epoch):
    noise = tf.random.normal((25, latent_dim))
    generated_images = generator(noise, training=False)

    generated_images = (generated_images + 1) / 2.0

    plt.figure(figsize=(5,5))
    for i in range(25):
        plt.subplot(5,5,i+1)
        plt.imshow(generated_images[i, :, :, 0], cmap='gray')
        plt.axis('off')

    plt.suptitle(f"Generated Images - Epoch {epoch}")
    plt.show()


# -----------------------------
# Training Loop
# -----------------------------
epochs = 30

for epoch in range(epochs):
    for real in dataset:
        batch = real.shape[0]

        # -----------------
        # Train Discriminator
        # -----------------
        noise = tf.random.normal((batch, latent_dim))
        fake = generator(noise, training=True)

        labels_real = tf.ones((batch, 1))
        labels_fake = tf.zeros((batch, 1))

        discriminator.trainable = True
        d_loss_real = discriminator.train_on_batch(real, labels_real)
        d_loss_fake = discriminator.train_on_batch(fake, labels_fake)
        d_loss = 0.5 * (d_loss_real + d_loss_fake)

        # -----------------
        # Train Generator
        # -----------------
        noise = tf.random.normal((batch, latent_dim))
        misleading_labels = tf.ones((batch, 1))

        discriminator.trainable = False
        g_loss = gan.train_on_batch(noise, misleading_labels)

    print(f"Epoch {epoch+1}: D_loss={d_loss:.4f}, G_loss={g_loss:.4f}")

    # Show generated images every 5 epochs
    if (epoch + 1) % 5 == 0:
        generate_and_plot_images(generator, epoch+1)