# -*- coding: utf-8 -*-
"""205124066_LAB_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1st0SmX2e93Q_SHaJ3fP32IuSN96P4fa9

# LSTM FOR Daily Climate Time Series Data (Delhi) **DATASET**
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

# Load dataset
data = pd.read_csv("DailyDelhiClimateTrain.csv")

# Use temperature column
series = data["meantemp"].values.reshape(-1,1)

# Normalize data
scaler = MinMaxScaler()
series = scaler.fit_transform(series)

# Window size
window_size = 30
horizon = 1

# Create dataset
def make_dataset(series, window_size, horizon):
    X, y = [], []
    for i in range(len(series) - window_size - horizon + 1):
        X.append(series[i:i+window_size])
        y.append(series[i+window_size:i+window_size+horizon])
    return np.array(X), np.array(y)

X, y = make_dataset(series, window_size, horizon)

# Train test split
split = int(0.8 * len(X))
X_train, y_train = X[:split], y[:split]
X_test, y_test = X[split:], y[split:]

# Build LSTM model
model = keras.Sequential([
    layers.LSTM(64, input_shape=(window_size,1)),
    layers.Dense(horizon)
])

# Compile model
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

# Train model
history = model.fit(
    X_train,
    y_train,
    epochs=500,
    batch_size=32,
    validation_split=0.2
)

# Evaluate
test_loss, test_mae = model.evaluate(X_test, y_test)

print("Test MAE:", test_mae)

# Predictions
predictions = model.predict(X_test)

# Inverse scale
# Predictions
predictions = model.predict(X_test)

# Inverse scaling
predictions = scaler.inverse_transform(predictions)

y_test_actual = scaler.inverse_transform(y_test.reshape(-1,1))

# Plot
plt.figure(figsize=(10,5))
plt.plot(y_test_actual[:100], label="Actual Temperature")
plt.plot(predictions[:100], label="Predicted Temperature")
plt.legend()
plt.show()

# Calculate accuracy based on tolerance
tolerance = 2  # degrees

correct = np.abs(predictions - y_test_actual) <= tolerance
accuracy = np.mean(correct) * 100

print("Accuracy:", accuracy, "%")



"""### Convert MAE Back to Real Temperature Error"""

temp_range = scaler.data_max_[0] - scaler.data_min_[0]
real_mae = test_mae * temp_range

print("Real MAE (°C):", real_mae)