# -*- coding: utf-8 -*-
"""205124066_LAB4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqK5cLkH5_gJRaPFHyQWCCt12YhSDG8Q
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
img_size = (224 , 224)

train_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/train", image_size = img_size , batch_size = 32 , label_mode = "binary")



import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))
for images, labels in train_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(int(labels[i]))
        plt.axis("off")

"""The above plot shows 9 images from the `train_ds` along with their labels.

Let's also check the shape of the image and the label type:
"""

for images, labels in train_ds.take(1):
    print("Image shape:", images[0].shape)
    print("Label type:", labels[0].dtype)
    print("Label value:", labels[0].numpy())

val_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/valid", image_size = img_size , batch_size = 32 , label_mode = "binary")

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))
for images, labels in val_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(int(labels[i]))
        plt.axis("off")

test_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/test", image_size = img_size , batch_size = 32 , label_mode = "binary")

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 10))
for images, labels in test_ds.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(int(labels[i]))
        plt.axis("off")

data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
])

base_model = keras.applications.DenseNet121(
    include_top=False,
    weights="imagenet",
    input_shape=img_size + (3,)
)

base_model.trainable = False
inputs = keras.Input(shape=img_size + (3,))
x = data_augmentation(inputs)
x = keras.applications.densenet.preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(256, activation="relu")(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)
# class_weight or pos_weight equivalent: use class_weight in model.fit
model.compile(
    optimizer=keras.optimizers.Adam(1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy", keras.metrics.AUC(name="auc")]
)
# Example class weights (compute from dataset first)
class_weight = {0: 1.0, 1: 2.0}
model.fit(train_ds, epochs=10, validation_data=val_ds, class_weight=class_weight)
test_metrics = model.evaluate(test_ds)
print("Test:", test_metrics)

print(f"Test Accuracy: {test_metrics[1]:.4f}")



"""# Task
Analyze the class distribution in the `train_ds` to understand class balance.

## Check Class Distribution in Training Data

### Subtask:
Calculate and print the number of samples for each class in the `train_ds` to understand class balance.

**Reasoning**:
To calculate the number of samples for each class, I need to iterate through the `train_ds`, extract labels, and count them. I will use `tf.cast` to convert `float32` labels to `int32` before using `np.bincount` to sum up the occurrences of each class. `np.bincount` is suitable for counting non-negative integers.
"""

import numpy as np

class_0_count = 0
class_1_count = 0

for _, labels in train_ds:
    # Convert labels from float32 to int32 for bincount
    int_labels = tf.cast(labels, dtype=tf.int32).numpy().flatten()
    counts = np.bincount(int_labels, minlength=2)

    if len(counts) > 0:
        class_0_count += counts[0]
    if len(counts) > 1:
        class_1_count += counts[1]

print(f"Total samples in Class 0: {class_0_count}")
print(f"Total samples in Class 1: {class_1_count}")

"""**Reasoning**:
The `train_ds` dataset, being a `tf.data.Dataset` object, is consumed after iteration (e.g., by `model.fit`). To accurately count all samples again, the `train_ds` needs to be re-initialized to ensure a fresh iteration over the entire dataset. Then, the original counting logic will be applied to the re-initialized dataset.


"""

train_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/train", image_size = img_size , batch_size = 32 , label_mode = "binary")

import numpy as np

class_0_count = 0
class_1_count = 0

for _, labels in train_ds:
    # Convert labels from float32 to int32 for bincount
    int_labels = tf.cast(labels, dtype=tf.int32).numpy().flatten()
    counts = np.bincount(int_labels, minlength=2)

    if len(counts) > 0:
        class_0_count += counts[0]
    if len(counts) > 1:
        class_1_count += counts[1]

print(f"Total samples in Class 0: {class_0_count}")
print(f"Total samples in Class 1: {class_1_count}")

"""## Check Class Distribution in Validation Data

### Subtask:
Calculate and print the number of samples for each class in the `val_ds` to understand class balance in the validation set.

**Reasoning**:
To calculate the class distribution in the `val_ds`, I will iterate through the dataset, extract the labels, convert them to integers, and then use `np.bincount` to count the occurrences of each class. Finally, I will print the total counts for each class.
"""

import numpy as np

class_0_count = 0
class_1_count = 0

for _, labels in val_ds:
    # Convert labels from float32 to int32 for bincount
    int_labels = tf.cast(labels, dtype=tf.int32).numpy().flatten()
    counts = np.bincount(int_labels, minlength=2)

    if len(counts) > 0:
        class_0_count += counts[0]
    if len(counts) > 1:
        class_1_count += counts[1]

print(f"Total samples in Class 0 (val_ds): {class_0_count}")
print(f"Total samples in Class 1 (val_ds): {class_1_count}")

"""**Reasoning**:
Since `val_ds` was consumed during the class counting process, it needs to be re-initialized to ensure it can be iterated upon again for future operations. After re-initialization, the class distribution will be recounted and printed to confirm the class balance.


"""

val_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/valid", image_size = img_size , batch_size = 32 , label_mode = "binary")

import numpy as np

class_0_count = 0
class_1_count = 0

for _, labels in val_ds:
    # Convert labels from float32 to int32 for bincount
    int_labels = tf.cast(labels, dtype=tf.int32).numpy().flatten()
    counts = np.bincount(int_labels, minlength=2)

    if len(counts) > 0:
        class_0_count += counts[0]
    if len(counts) > 1:
        class_1_count += counts[1]

print(f"Total samples in Class 0 (val_ds): {class_0_count}")
print(f"Total samples in Class 1 (val_ds): {class_1_count}")

"""## Check Class Distribution in Test Data

### Subtask:
Calculate and print the number of samples for each class in the `test_ds` to understand class balance in the test set.

**Reasoning**:
To calculate the class distribution in the `test_ds`, I will iterate through the dataset, extract the labels, convert them to integers, and then use `np.bincount` to count the occurrences of each class. Finally, I will print the total counts for each class.
"""

import numpy as np

class_0_count = 0
class_1_count = 0

for _, labels in test_ds:
    # Convert labels from float32 to int32 for bincount
    int_labels = tf.cast(labels, dtype=tf.int32).numpy().flatten()
    counts = np.bincount(int_labels, minlength=2)

    if len(counts) > 0:
        class_0_count += counts[0]
    if len(counts) > 1:
        class_1_count += counts[1]

print(f"Total samples in Class 0 (test_ds): {class_0_count}")
print(f"Total samples in Class 1 (test_ds): {class_1_count}")

"""**Reasoning**:
Since `test_ds` was consumed during the class counting process, it needs to be re-initialized to ensure it can be iterated upon again for future operations. After re-initialization, the class distribution will be recounted and printed to confirm the class balance.


"""

test_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/test", image_size = img_size , batch_size = 32 , label_mode = "binary")

import numpy as np

class_0_count = 0
class_1_count = 0

for _, labels in test_ds:
    # Convert labels from float32 to int32 for bincount
    int_labels = tf.cast(labels, dtype=tf.int32).numpy().flatten()
    counts = np.bincount(int_labels, minlength=2)

    if len(counts) > 0:
        class_0_count += counts[0]
    if len(counts) > 1:
        class_1_count += counts[1]

print(f"Total samples in Class 0 (test_ds): {class_0_count}")
print(f"Total samples in Class 1 (test_ds): {class_1_count}")

"""## Evaluate Model with Detailed Metrics

### Subtask:
Predict on the test dataset and calculate precision, recall, and F1-score. This will provide a more comprehensive view of the model's performance beyond just accuracy.

**Reasoning**:
First, I'll re-initialize the `test_ds` to ensure it's available for iteration. Then, I will import the necessary `sklearn.metrics` for precision, recall, and F1-score calculation. Next, I will extract the true labels from the `test_ds`, make predictions using the trained `model`, convert the probabilities to binary predictions, and finally compute and print the precision, recall, and F1-score as per the instructions.
"""

test_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/test", image_size = img_size , batch_size = 32 , label_mode = "binary")

import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

# 2. Extract true labels from the test_ds
true_labels = []
for _, labels in test_ds:
    true_labels.append(labels.numpy())
true_labels = np.concatenate(true_labels).flatten()

# 3. Make predictions on the test_ds
predictions = model.predict(test_ds)

# 4. Convert predicted probabilities to binary class predictions
binary_predictions = (predictions > 0.5).astype(int).flatten()

# 5. Calculate precision score
precision = precision_score(true_labels, binary_predictions)

# 6. Calculate recall score
recall = recall_score(true_labels, binary_predictions)

# 7. Calculate F1-score
f1 = f1_score(true_labels, binary_predictions)

# 8. Print the calculated metrics
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

"""**Reasoning**:
The previous code resulted in `UndefinedMetricWarning` for precision, recall, and F1-score because `test_ds` contained only samples from Class 0, making metrics for Class 1 (the positive class in binary classification) ill-defined. To provide a more comprehensive view and handle this imbalance gracefully, I will use `sklearn.metrics.classification_report` which automatically calculates and displays per-class metrics, including support, and handles `zero_division` by showing 0.0 for absent classes, thus fulfilling the instruction to get a comprehensive view beyond accuracy.


"""

test_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/test", image_size = img_size , batch_size = 32 , label_mode = "binary")

import numpy as np
from sklearn.metrics import classification_report

# 2. Extract true labels from the test_ds
true_labels = []
for _, labels in test_ds:
    true_labels.append(labels.numpy())
true_labels = np.concatenate(true_labels).flatten()

# 3. Make predictions on the test_ds
predictions = model.predict(test_ds)

# 4. Convert predicted probabilities to binary class predictions
binary_predictions = (predictions > 0.5).astype(int).flatten()

# 5. Generate and print the classification report
# The classification report will show precision, recall, and f1-score for each class.
# It also handles cases where a class has no true samples or no predicted samples.
print("Classification Report:")
print(classification_report(true_labels, binary_predictions, target_names=['Class 0', 'Class 1'], zero_division=0))

"""**Reasoning**:
The `ValueError` occurred because `classification_report` inferred only one class from `true_labels` and `binary_predictions` (both contained only zeros), while `target_names` specified two classes. To align this and force the report to consider both classes, even if one is absent, I need to explicitly pass the `labels=[0, 1]` parameter to `classification_report`.


"""

test_ds = tf.keras.preprocessing.image_dataset_from_directory("drive/MyDrive/tomoto_leaf/test", image_size = img_size , batch_size = 32 , label_mode = "binary")

import numpy as np
from sklearn.metrics import classification_report

# 2. Extract true labels from the test_ds
true_labels = []
for _, labels in test_ds:
    true_labels.append(labels.numpy())
true_labels = np.concatenate(true_labels).flatten()

# 3. Make predictions on the test_ds
predictions = model.predict(test_ds)

# 4. Convert predicted probabilities to binary class predictions
binary_predictions = (predictions > 0.5).astype(int).flatten()

# 5. Generate and print the classification report
# The classification report will show precision, recall, and f1-score for each class.
# It also handles cases where a class has no true samples or no predicted samples.
print("Classification Report:")
print(classification_report(true_labels, binary_predictions, labels=[0, 1], target_names=['Class 0', 'Class 1'], zero_division=0))

"""## Final Task

### Subtask:
Summarize the findings from the class distribution analysis and the detailed evaluation metrics to understand why the model achieved 100% accuracy and suggest next steps.

## Summary:

### Q&A
The model achieved 100% accuracy because all training, validation, and test datasets contained exclusively samples from Class 0 and no samples from Class 1. Therefore, the model correctly classified all available samples as Class 0, leading to perfect accuracy on the given datasets, but effectively failing to learn to differentiate between classes.

### Data Analysis Key Findings
*   The `train_ds` was found to be severely imbalanced, containing 645 samples for Class 0 and 0 samples for Class 1.
*   Similarly, the `val_ds` also showed extreme imbalance, with 61 samples for Class 0 and 0 samples for Class 1.
*   The `test_ds` exhibited the same issue, containing 31 samples for Class 0 and 0 samples for Class 1.
*   The model's evaluation metrics reflected this imbalance:
    *   **Accuracy:** 1.00 (100%), as all 31 samples in the test set belonged to Class 0 and were correctly predicted.
    *   **Class 0 Performance:** Precision, Recall, and F1-score for Class 0 were all 1.00, indicating perfect classification of this class.
    *   **Class 1 Performance:** Precision, Recall, and F1-score for Class 1 were all 0.00, due to the complete absence of Class 1 samples in the test dataset.
    *   **Macro Average:** Precision, Recall, and F1-score were 0.50, demonstrating that when both classes are considered equally, the model's performance is poor due to its inability to classify Class 1.
    *   **Weighted Average:** Precision, Recall, and F1-score were 1.00, as this average is weighted by the number of samples per class, and only Class 0 had samples.

### Insights or Next Steps
*   The current model performance is highly misleading; the 100% accuracy is an artifact of extreme data imbalance, not an indication of a robust classification model. The model has essentially learned to always predict Class 0.
*   The critical next step is to address the severe class imbalance by acquiring or generating data for Class 1 and re-balancing the training, validation, and test datasets before retraining and re-evaluating the model.
"""