# -*- coding: utf-8 -*-
"""205124066_LAB_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROmfOkTZGy5DyBLqenmt9v1muPEwu9cA
"""

import gymnasium as gym
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import random
from collections import deque
import matplotlib.pyplot as plt

# Environment
env = gym.make("CartPole-v1")
n_actions = int(env.action_space.n)
state_shape = int(env.observation_space.shape[0])

# Q Network
def build_q_net():
    inputs = keras.Input(shape=(state_shape,))
    x = layers.Dense(128, activation="relu")(inputs)
    x = layers.Dense(128, activation="relu")(x)
    outputs = layers.Dense(int(n_actions))(x)
    return keras.Model(inputs, outputs)

q_net = build_q_net()
target_net = build_q_net()
target_net.set_weights(q_net.get_weights())

optimizer = keras.optimizers.Adam(learning_rate=1e-3)
loss_fn = keras.losses.Huber()

replay_buffer = deque(maxlen=50000)

gamma = 0.99
epsilon, epsilon_min, epsilon_decay = 1.0, 0.05, 0.995
batch_size = 64

episode_rewards = []

# Action selection
def select_action(state, epsilon):
    if np.random.rand() < epsilon:
        return env.action_space.sample()
    state = np.array(state, dtype=np.float32)
    q_values = q_net(np.expand_dims(state, axis=0), training=False)
    return int(tf.argmax(q_values[0]).numpy())

# Training step
def train_step():
    if len(replay_buffer) < batch_size:
        return

    batch = random.sample(replay_buffer, batch_size)
    states, actions, rewards, next_states, dones = map(np.array, zip(*batch))

    states = states.astype(np.float32)
    next_states = next_states.astype(np.float32)
    rewards = rewards.astype(np.float32)
    dones = dones.astype(np.float32)

    next_q = target_net(next_states, training=False)
    max_next_q = tf.reduce_max(next_q, axis=1)

    targets = rewards + (1 - dones) * gamma * max_next_q

    with tf.GradientTape() as tape:
        q_values = q_net(states, training=True)
        indices = tf.range(batch_size)
        action_indices = tf.stack([indices, actions], axis=1)
        q_selected = tf.gather_nd(q_values, action_indices)

        loss = loss_fn(targets, q_selected)

    grads = tape.gradient(loss, q_net.trainable_variables)
    optimizer.apply_gradients(zip(grads, q_net.trainable_variables))


# Training loop
num_episodes = 400

for ep in range(num_episodes):
    state, _ = env.reset()
    total_reward = 0
    done = False

    while not done:
        action = select_action(state, epsilon)
        next_state, reward, terminated, truncated, _ = env.step(action)

        done = terminated or truncated

        replay_buffer.append((state, action, reward, next_state, float(done)))

        state = next_state
        total_reward += reward

        train_step()

    episode_rewards.append(total_reward)

    epsilon = max(epsilon_min, epsilon * epsilon_decay)

    if ep % 10 == 0:
        target_net.set_weights(q_net.get_weights())
        print(f"Episode {ep}, Reward: {total_reward}, Epsilon: {epsilon:.3f}")

# Plot Rewards
plt.figure(figsize=(10,5))
plt.plot(episode_rewards, label="Reward per Episode")

window = 10
moving_avg = np.convolve(episode_rewards, np.ones(window)/window, mode='valid')
plt.plot(range(window-1, len(episode_rewards)), moving_avg, label="Moving Avg (10)")

plt.xlabel("Episodes")
plt.ylabel("Reward")
plt.title("Training Performance")
plt.legend()
plt.show()

# Test the trained agent
test_env = gym.make("CartPole-v1", render_mode="human")

state, _ = test_env.reset()
done = False

while not done:
    state = np.array(state, dtype=np.float32)
    q_values = q_net(np.expand_dims(state, axis=0), training=False)
    action = int(tf.argmax(q_values[0]).numpy())

    state, _, terminated, truncated, _ = test_env.step(action)
    done = terminated or truncated

test_env.close()