# -*- coding: utf-8 -*-
"""205124066_LAB_07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OiLn0tSTt9ZmskrM95gOkDnPn6OVJU5i
"""

!pip install -U transformers datasets evaluate torch

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset, DatasetDict
import evaluate

model_name = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

texts = [
    "I love this movie!",
    "This is terrible.",
    "Amazing performance!",
    "Worst experience ever.",
    "I really enjoyed the book.",
    "The service was awful."
]

labels = [1, 0, 1, 0, 1, 0]

dataset = Dataset.from_dict({"text": texts, "label": labels})

dataset = dataset.train_test_split(test_size=0.3)
dataset

def tokenize(batch):
    return tokenizer(batch["text"], padding="max_length", truncation=True, max_length=64)

tokenized = dataset.map(tokenize, batched=True)

tokenized = tokenized.rename_column("label", "labels")


tokenized.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = torch.argmax(torch.tensor(logits), dim=-1)

    return {
        "accuracy": accuracy.compute(predictions=predictions, references=labels),
        "f1": f1.compute(predictions=predictions, references=labels),
    }

import transformers
print(transformers.__version__)

training_args = TrainingArguments(
    output_dir="./bert-output",

    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,

    num_train_epochs=3,
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["test"],   # still works even without eval_strategy
    compute_metrics=compute_metrics,
)

trainer.train()

# ---------------------------------------------------
# 9. Prediction Function
# ---------------------------------------------------

def predict(text):
    device = model.device   # auto-detect CUDA or CPU

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=64
    ).to(device)

    with torch.no_grad():
        logits = model(**inputs).logits

    pred = torch.argmax(logits, dim=-1).item()
    return "Positive" if pred == 1 else "Negative"

# Test
print(predict("I absolutely hated the movie!"))
print(predict("I enjoyed the movie!"))
print(predict("Loved the movie!"))
print(predict("Does not Love the movie!"))
print(predict("This was the worst thing ever."))

