# -*- coding: utf-8 -*-
"""205124066_LAB_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JS5pMEn69POeBS_bX8vz5XNWzL5Se0fT
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

# =========================
# 1. Load & preprocess data
# =========================
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = x_train.astype("float32") / 255.0
x_test  = x_test.astype("float32") / 255.0

# Add channel dimension
x_train = x_train[..., None]
x_test  = x_test[..., None]

# Train only on digits 0–8 (exclude 9)
normal_mask = y_train != 9
x_train_normal = x_train[normal_mask]

print("Training samples:", x_train_normal.shape)

# =========================
# 2. Build Autoencoder
# =========================
input_shape = (28, 28, 1)

inputs = keras.Input(shape=input_shape)

# Encoder
x = layers.Conv2D(16, 3, padding="same", activation="relu")(inputs)
x = layers.MaxPool2D(2)(x)
x = layers.Conv2D(32, 3, padding="same", activation="relu")(x)
x = layers.MaxPool2D(2)(x)

latent = x

# Decoder
x = layers.Conv2DTranspose(16, 2, strides=2, activation="relu")(latent)
x = layers.Conv2DTranspose(1, 2, strides=2, activation="sigmoid")(x)

outputs = x

autoencoder = keras.Model(inputs, outputs)
autoencoder.compile(optimizer="adam", loss="mse")

autoencoder.summary()

# =========================
# 3. Train model
# =========================
autoencoder.fit(
    x_train_normal, x_train_normal,
    epochs=20,
    batch_size=128,
    validation_split=0.1
)

# =========================
# 4. Reconstruction
# =========================
recon = autoencoder.predict(x_test)

# Compute reconstruction error
errors = tf.reduce_mean(tf.square(x_test - recon), axis=(1,2,3)).numpy()

# =========================
# 5. Visualization
# =========================

# ---- Original vs Reconstructed ----
n = 10
plt.figure(figsize=(20, 4))

for i in range(n):
    # Original
    ax = plt.subplot(2, n, i + 1)
    plt.imshow(x_test[i].squeeze(), cmap="gray")
    plt.title("Original")
    plt.axis("off")

    # Reconstructed
    ax = plt.subplot(2, n, i + 1 + n)
    plt.imshow(recon[i].squeeze(), cmap="gray")
    plt.title("Reconstructed")
    plt.axis("off")

plt.show()

# ---- Error distribution ----
plt.hist(errors, bins=50)
plt.title("Reconstruction Error Distribution")
plt.xlabel("Error")
plt.ylabel("Count")
plt.show()

# =========================
# 6. Anomaly Detection
# =========================

# Threshold (simple method)
threshold = errors.mean() + 2 * errors.std()
print("Threshold:", threshold)

# Predictions
y_pred = (errors > threshold).astype(int)

# True labels (9 = anomaly)
y_true = (y_test == 9).astype(int)

# =========================
# 7. Accuracy
# =========================
accuracy = np.mean(y_pred == y_true)
print("Detection Accuracy:", accuracy)

# =========================
# 8. Show detected anomalies
# =========================
anomaly_indices = np.where(y_pred == 1)[0]

plt.figure(figsize=(10, 4))
for i, idx in enumerate(anomaly_indices[:10]):
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_test[idx].squeeze(), cmap="gray")
    plt.title(f"Err: {errors[idx]:.4f}")
    plt.axis("off")

plt.show()