# -*- coding: utf-8 -*-
"""205124066_LAB5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S_u-SC1SsIMTDbvI8LyOYQVgzAfuzdIV
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
# Load IMDb
vocab_size = 20000
max_len = 200
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words=vocab_size)
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen=max_len)
x_test  = keras.preprocessing.sequence.pad_sequences(x_test, maxlen=max_len)
model = keras.Sequential([
    layers.Embedding(vocab_size, 100, input_length=max_len),
    layers.Bidirectional(layers.LSTM(128, return_sequences=False)),
    layers.Dense(64, activation="relu"),
    layers.Dense(1, activation="sigmoid")
])
model.compile(
    optimizer=keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
model.summary()
model.fit(x_train, y_train, epochs=5, batch_size=64, validation_split=0.2)
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print("Test accuracy:", test_acc)

model.summary()